### ISSUE TITLE
How to set specified number of training samples?

### ISSUE THREAD

**Issue by yuhua666** [xiachangxue/DeepHyperX#5]
For example, I want to specify 25 training samples for each category instead of 1% training samples. What should I do?

**Comment by xiachangxue** [comment]
You need modify the main.py file. #377, the mode="random", the random should be modified to "fixed". Then, you can use the 5/10/15 training samples for each category instead of 0.1 training samples

**Comment by yuhua666** [comment]
Is it modified like this?
train_gt, val_gt = sample_gt(train_gt, 25, mode="fixed")

**Comment by yuhua666** [comment]
An error occurs.
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.

**Comment by yuhua666** [comment]
it works.
